import type { Metadata } from "next";
import '../globals.css';
import ProfileLayout from "@/layouts/ProfileLayouts";

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <ProfileLayout><div>{children}</div></ProfileLayout>;
}   
