import type { Metadata } from "next";
import { SidebarProvider, SidebarInset, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar";
import '../globals.css';

export const metadata: Metadata = {
  title: "Ticketing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
        <SidebarProvider>
          <nav>
            <AppSidebar />
            <SidebarInset />
          </nav>

          <main>
            <SidebarTrigger className="fixed top-3 z-20"/>
            {children}
          </main>
        </SidebarProvider>
      
  );
}
