import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar";
import '../globals.css';
import { ClientOnly } from "@/lib/ClientOnly";
import AuthGuard from "@/hooks/use-auth";
// import AuthGuard from "@/hooks/use-auth";

export const metadata: Metadata = {
  title: "Ticketing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientOnly>
      <AuthGuard allowedLevels={[1, 2]}>
        <SidebarProvider>
          <nav>
            <AppSidebar />
          </nav>
          <main className="w-full">
            <SidebarTrigger className="fixed top-2 z-20"/>
            {children}
          </main>
        </SidebarProvider>
      </AuthGuard>
    </ClientOnly>
  );
}
