import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation";
import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/toaster";
import { LenisProvider } from "@/context/LenisScroll";

import 'swiper/css'
import 'swiper/swiper-bundle.css';
import 'swiper/css/navigation';

export const metadata: Metadata = {
  title: "Travel Link",
  description: "Generated by create next app",
};

const MontserratFont = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <head>
        <link 
          rel="icon" 
          href="/travel-ticket-logo.svg"
          sizes="any"
          type="image/svg+xml"
        />
      </head>
      <body
         className={`${MontserratFont.className} antialiased`}
      >
          <nav>
            <Navbar/>
          </nav>

          <main>
            <LenisProvider>
            {children}
            <Toaster />
            </LenisProvider>
          </main>

          <footer>
            <Footer/>
          </footer>
      </body>
    </html>
  );
}
